In [1]:
import calculator
import numpy as np

In [7]:
dir(calculator)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'cos',
 'cos_',
 'exp',
 'exponential',
 'log',
 'relu',
 'sigmoid',
 'sin',
 'sin_',
 'softmax',
 'tan',
 'tan_',
 'tanh']

In [6]:
calculator.sin_(0)

sin theta : 0.0


0.0

In [7]:
calculator.dsin(0)

AttributeError: module 'calculator' has no attribute 'dsin'

In [8]:
from calculator import derivatives
derivatives.dsin(30)

derivative of sin theta :0.8660254037844387


0.8660254037844387

In [9]:
calculator.cos_(0)

cos theta : 1.0


1.0

In [11]:
derivatives.dcos(30)

derivative of cos theta : -0.49999999999999994


-0.49999999999999994

In [3]:
calculator.tan_(45)

tan theta : 0.9999999999999999


0.9999999999999999

In [14]:
derivatives.dtan(0)

derivative of tan theta :1.0


mpf('1.0')

In [3]:
calculator.tanh(30)

tanh value : 0.48047277815645156


1.0

In [2]:
from calculator import derivatives
derivatives.dtanh(30)

derivative of tanh : 0.7691459094506212


0.7691459094506212

In [7]:
calculator.softmax([3,4,5]) == np.array([0.09003057, 0.24472847, 0.66524096])

[0.09003057 0.24472847 0.66524096]


array([False, False, False])

In [3]:
return_ = calculator.softmax([3,4,5])
return_[0]

[0.09003057 0.24472847 0.66524096]


0.09003057317038046

In [10]:
np.array([0.09003057, 0.24472847, 0.66524096])

array([0.09003057, 0.24472847, 0.66524096])

In [6]:
from calculator import derivatives
return_ = derivatives.dsoftmax([3,4,5])

[0.09003057 0.24472847 0.66524096]
Derivative of softmax is: [[ 0.08192507 -0.02203304 -0.05989202]
 [-0.02203304  0.18483645 -0.1628034 ]
 [-0.05989202 -0.1628034   0.22269543]]


In [10]:
return_[0][2]

-0.059892024544818935

In [11]:
calculator.sigmoid(0)

Sigmoid of 0 is 0.5


0.5

In [12]:
derivatives.dsigmoid(0)

Sigmoid of 0 is 0.5
Sigmoid of 0 is 0.5
Derivative of sigmoid for 0 is 0.25
Sigmoid of 0 is 0.5
Sigmoid of 0 is 0.5


0.25

In [14]:
calculator.relu([-0.5, 0.5])

TypeError: Enter a valid number type